version: "3"
services:
    php:
        container_name: php
        build: ./docker/php
        ports:
            - "8080:80"
        volumes: 
            - ./:/var/www/html
        working_dir: /var/www/html

    nginx:
        depends_on:
            - php
        container_name: nginx
        build: ./docker/nginx
        command: nginx -g "daemon off;"
        # links: 
        #     - php
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html
        
