version: '3'
services:
    php:
        # container_name: php
        build: ./docker/php
        # restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        networks:
            - labnet
    nginx:
        container_name: nginx
        build: ./docker/nginx
        command: nginx -g "daemon off;"
        restart: always
        links: 
            - php
        ports:
            - "80:80"
            # - "443:443"
        volumes:
            - ./:/var/www:rw
        networks:
            - labnet
networks:
    labnet: 
        driver: bridge
