version: '3.5'
services:
    php:
        container_name: php
        build: ./docker/php
        # command: /bin/bash -c "/etc/start.sh;"
        ports:
            - "8080:80"
        volumes: 
            - ./:/var/www
        working_dir: /var/www
        networks:
            - my_network

    nginx:
        container_name: nginx
        build: ./docker/nginx
        command: nginx -g "daemon off;"
        # links: 
        #     - php
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
        networks:
            - my_network
                
    networks:
        my_network:
            driver: bridge
