version: "3"
services:
    php:
        container_name: php
        build: ./docker/php
        ports:
            - "8080:80"
        volumes: 
            - ./:/var/www
        command: bash -c "chmod +x /var/www/docker/php/start.sh && /bin/sh -c /var/www/docker/php/start.sh;"
        working_dir: /var/www

    nginx:
        depends_on:
            - php
        container_name: nginx
        build: ./docker/nginx
        command: nginx -g "daemon off;"
        # links: 
        #     - php
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
        
