#!/bin/sh
echo "Hi Enjoyable Programming this job with bash runs each minute - $(date)"
echo "You can schedule any thing you want here"
# mkdir -p "/etc/nginx/sites/ssl/dummy/bon.com"


openssl req -x509 -out "/var/www/docker/nginx/nginx-selfsigned.crt" -keyout "/var/www/docker/nginx/nginx-selfsigned.key" \
  -newkey rsa:2048 -nodes -sha256 \
  -subj '/CN=bon.com' -extensions EXT -config <( \
   printf "[dn]\nCN=bon.com\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=DNS:bon.com\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth")

# docker compose exec --no-TTY nginx nginx -s reload

# echo "Starting cron..."
# crond -f